
import java.awt.Color;
import static java.lang.Thread.sleep;

import javax.swing.*;
import javax.swing.text.DefaultCaret;

public class Fabrica extends JFrame {

    public Fabrica() {
        initComponents();
        super.setTitle("Fabrica de Papel");
        papel.setValue(5);
        cajas.setValue(1);
        btnStart.setBackground(new Color(0, 153, 51));
        DefaultCaret caret = (DefaultCaret) texto.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new JPanel();
        panel_opcion = new JPanel();
        btnStart = new JButton();
        cajas = new JSpinner();
        papel = new JSpinner();
        lbCajas = new JLabel();
        lbPapel = new JLabel();
        jScrollPane1 = new JScrollPane();
        texto = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        cajas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        GroupLayout panel_opcionLayout = new GroupLayout(panel_opcion);
        panel_opcion.setLayout(panel_opcionLayout);
        panel_opcionLayout.setHorizontalGroup(
            panel_opcionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionLayout.createSequentialGroup()
                .addGroup(panel_opcionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panel_opcionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cajas, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(papel, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnStart, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        panel_opcionLayout.setVerticalGroup(
            panel_opcionLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionLayout.createSequentialGroup()
                .addGroup(panel_opcionLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cajas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(papel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        lbCajas.setText("Cajas");

        lbPapel.setText("Papel");

        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        texto.setColumns(20);
        texto.setRows(5);
        texto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(texto);

        GroupLayout panelMainLayout = new GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 277, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(panel_opcion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbCajas)
                        .addGap(38, 38, 38)
                        .addComponent(lbPapel))))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelMainLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCajas)
                    .addComponent(lbPapel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_opcion, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelMain, GroupLayout.PREFERRED_SIZE, 440, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        this.texto.setText("");
        
        Thread aux = new Thread(() -> {
            btnStart.setEnabled(false);
            
            Fabrica2 fMain = new Fabrica2(texto, (Integer) cajas.getValue(), (Integer) papel.getValue());

            fMain.start();

            try {
                sleep(1000 * Math.max(fMain.cantPapel, fMain.cantCajas));
                fMain.join();
            } catch (InterruptedException e) {
            }

            texto.append("\n\nCaja Actual tiene:  " + fMain.cajita.getCantPapelActual());
            texto.append("\nCantidad de cajas llenas:  " + fMain.cajita.getCantCajaActual());
            texto.append("\nCantidad Maxima de cajas:  " + fMain.cajita.getMaxCantCajas());

            System.out.println("\n\nCaja Actual tiene:  " + fMain.cajita.getCantPapelActual());
            System.out.println("Cantidad de cajas llenas:  " + fMain.cajita.getCantCajaActual());
            System.out.println("Cantidad Maxima de cajas:  " + fMain.cajita.getMaxCantCajas());

            while (!fMain.done) {
                if (fMain.g1.activeGroupCount() == 0) {
                    fMain.done = true;
                    btnStart.setEnabled(true);
                }
            }
        });

        aux.start();
    }//GEN-LAST:event_btnStartActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Fabrica frame = new Fabrica();
                frame.setVisible(true);
            }
        });

    }

    public JSpinner getCajas() {
        return cajas;
    }

    public JSpinner getPapel() {
        return papel;
    }

    public JTextArea getTexto() {
        return texto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnStart;
    private JSpinner cajas;
    private JScrollPane jScrollPane1;
    private JLabel lbCajas;
    private JLabel lbPapel;
    private JPanel panelMain;
    private JPanel panel_opcion;
    private JSpinner papel;
    private JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
